baseurl = "https://sxhinzvc.github.io/TIL/"
languageCode = "en-us"
title = "today i learned"
theme = "cactus"
publishDir = "docs"
copyright = "julia lee"

[permalinks]
  post = "/:year/:month/:day/:title/"
  page = "/:title/"

[[menu.main]]
  name = "posts"
  url = "/posts/"
[[menu.main]]
  name = "about"
  url = "/about/"

[[params.social]]
  name = "github"
  url = "https://github.com/sxhinzvc"
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/eejulialee"

[params]
  description = ""
  colortheme = "dark"
  [params.comments]
    enabled = false
